### ISSUE TITLE
bundling exclusions

### ISSUE THREAD

**Issue by dzearing** [brillout/gulp-jspm#1]
how would this work with bundling exclusions? E.g. code references react, but doesn't want it bundled. it would be nice to have an example.

**Comment by brillout** [comment]
see patch.

you can now do `jspm_gulp('- react')`.

I am curious; what is the reason for not bundling react?

**Comment by dzearing** [comment]
Awesome, thanks! I have a couple of scenarios I want this for:

For vendor content that doesn't frequently update, I do not want to include them in the primary code bundle. As the primary code changes, it uses hashing in the filenames to break cdn urls. If I update this code every 2 hours, I don't want revisiting users to have to download my unchanged vendor code again.

For external code living in other repos, normally you'd check in unbundled modules into libs and publish to npm. But that implies you know what the external code is at time of application bundling. Say you wanted to have "plugin" libraries be able to be consumed later outside of the application's bundling cadence. Well, those libraries should produce their own bundles. But if they just "bundle all" they'll include a duplicate copy of the vendor code (like react). So we would want their bundles to avoid, as much as possible, bundling content that is already loaded on the page's main bundles.

**Comment by brillout** [comment]
Ok that makes sense, thanks for the explanation.

Closing, feel free to re-open.
