### ISSUE TITLE
[baseURL] Path must be a string

### ISSUE THREAD

**Issue by Sin-Deus** [brillout/gulp-jspm#17]
Hi all!

I've run into a bit of an issue here. Whenever I try to run the gulp-jspm task (v 0.5.4), it fails with this error message:

    path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

    TypeError: Path must be a string. Received undefined
        at assertPath (path.js:8:11)
        at Object.win32.join (path.js:221:5)
        at Liftoff.<anonymous> (C:\...\node_modules\gulp-jspm\index.js:167:30)
        at Liftoff.<anonymous> (C:\...\node_modules\liftoff\index.js:196:12)
        at Liftoff.<anonymous> (C:\...\node_modules\liftoff\index.js:164:7)
        at doNTCallback0 (node.js:419:9)
        at process._tickCallback (node.js:348:13)

After some investigation, I found out this particular line of code in `gulp-jspm/index.js` (line 166):

    if (packageJSON && packageJSON.jspm && packageJSON.jspm.directories) {
        resolve(path.join(env.configBase, packageJSON.jspm.directories.baseURL));
    }

So, I tried to add a `baseURL` property under my `jspm.directories` object in `package.json`, so that it would look like that:

    "jspm": {
        "directories": {
            "packages": "src/jspm_packages",
            "baseURL": ""
        }
        ...
    }

If finally works! Yay! But here is the thing: whenever I run a `jspm` command (like `jspm install`), jspm overwrites my `package.json` file and friggin' _removes_ the `baseURL` property.

A quick fix would be testing if `packageJSON.jspm.directories.baseURL` is a string indeed, to prevent gulp-jspm from crashing.

What do you think? Thank you for your time!

**Comment by brillout** [comment]
Thanks for opening the issue.
Fix has been written and published under `0.5.5`

**Comment by Sin-Deus** [comment]
Thank you, works like a charm!
