### ISSUE TITLE
What is this pass()?

### ISSUE THREAD

**Issue by unional** [brillout/gulp-jspm#28]
https://github.com/brillout/gulp-jspm/blob/master/README.md#original-entry-point
```js
gulp.src('src/main.js')
    .pipe(gulp_jspm())
    .pipe(pass(function(vinyl_file){  // <-- here
        assert( vinyl_file.relative === 'main.bundle.js' );
        assert( vinyl_file.originalEntryPoint.relative === 'main.js' );
    }));
```

**Comment by brillout** [comment]
the original file that was passed to `gulp-jspm`

**Comment by unional** [comment]
Oh, I mean what is this pass function.

**Comment by brillout** [comment]
pass is actually just a function that is defined bellow; https://github.com/brillout/gulp-jspm/blob/master/demo/gulpfile.js#L23-L40

As for `tape-run` I would say that it is a use case that is probably too specific to be included as example. Thanks though

**Comment by unional** [comment]
Thanks.
