### ISSUE TITLE
Recommend creating "options"

### ISSUE THREAD

**Issue by dzearing** [brillout/gulp-jspm#3]
The way that arithmetic was added works, but it should be refactored before too many people consume it. Make an options bag, and additionally add the "name" of the bundle to be specifiable. Example:

```javascript
// create app bundle
.pipe(jspm({
   name: 'app.js',
   arithmetic: excludedPackages,
}))
```

```javascript
// later create a vendor bundle with a different filename
.pipe(jspm({
  name: 'vendor.js',
  arithmetic: includedPackages
}))
```

Later down the road as jspm matures, you will want more options... having a property bag rather than a single param would be future proof.

**Comment by brillout** [comment]
yes you are right, thanks!

**Comment by dzearing** [comment]
nice job!
