### ISSUE TITLE
Support for arithmetic and selfExecutingBundle params at the same time

### ISSUE THREAD

**Issue by kmturley** [brillout/gulp-jspm#30]
If I run the gulp-jspm arithmetic demo:
https://github.com/brillout/gulp-jspm/blob/master/demo/gulpfile.js#L43

It runs fine using the code:

    gulp_jspm({arithmetic:'- message'})

But it fails if I use the params:

    gulp_jspm({arithmetic:'- message',selfExecutingBundle: true})

The error is:

    SFX Bundle input error

I opened this issue with jspm here, but the team say it should already be supported:
https://github.com/jspm/jspm-cli/issues/1761

In my case I'm wanting to use system js for my dev environment importing one js file:

    <script>
        System.import('{% static "web/components/all" %}');
    </script>

Then within all.js import angular and my other modules

    import angular from 'angular';
    import Comments from './comments/comments';

Then when creating the production build, exclude angular so I can use the CDN version.

Is this something you can add support for?

**Comment by brillout** [comment]
see reply at the issue at the JSPM repo

**Comment by brillout** [comment]
adressed in the jspm ticket
