### ISSUE TITLE
preserve original filename

### ISSUE THREAD

**Issue by brillout** [brillout/gulp-jspm#7]
@yelvert 
@jigfox

I'm open for this feature.
I would just like to know your specific use case and why this is needed for your use case.

It feels better to know the reason of a feature before implementing it.

**Comment by jigfox** [comment]
One use case would be to create multiple bundles, another one is to use a name I want, because I need to share this file, and than it should have a more explicit name.

**Comment by brillout** [comment]
> One use case would be to create multiple bundles

that's now covered with https://github.com/brillout/gulp-jspm/commit/9c0fdb135ef7d143f9570c83434c590b700b7f47

> I need to share this file, and than it should have a more explicit name.

would https://github.com/hparra/gulp-rename work for you?

**Comment by dzearing** [comment]
I think the output filename should not be defined by the gulp plugin but rather provided by either the options bag, or ideally just outputs a stream that can be piped to other things.

I intuitively expected this:

gulp.src('lib/index')
  .pipe(jspm())
  .pipe(gulp.dest('dist/library.js')
  .pipe(uglify())
  .pipe(gup.dest('dist/library.min.js');

**Comment by dzearing** [comment]
Actually gulp-rename is a good enough solution. Nevermind!

**Comment by brillout** [comment]
feel free to re-open
